extends Node2D

signal addGold(amount:int)
signal removeGold(amount:int)
signal saveGame()
signal loadGame()
signal newSaveGame()
signal windowSetup()
signal setState(state:int)
signal setTooltip(name:String, growth:float)
signal confirmRemove(decide:bool)
signal confirmUI()
signal mouseTooltip(text1:String,text2: String, image1:String, image2:String, requirementText:String, requirementPlay:bool, enable:bool)
signal collectSeed(rootType:String,stemType:String,flowerType:String, plantSpecialType:String)
signal changeGameSpeed()
signal gridToggle(value:bool)
signal generateMysterySeed(tier:int)
signal shopDescription(name:String, description:String, cost:int)
signal hideShopDesciption()
signal fillWater(enable:bool)
signal outOfWater(enable:bool)
signal waterBarEnable(enable:bool)
signal changeState(value:int)
signal plantOptions(value:bool)
